---
title: "Gauges Meter"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
```

Row 1 
-----------------------------------------------------------------------

### Data Entering Panel

```{r}
numericInput("rate","Enter Contact Rate", value = 0,min = 0,max = 100 )

numericInput("rating", label = "Enter Rating Value:",value = 0,min = 0,max = 50)

numericInput("cancellations", label = "Enter Cancellation Value:",value = 0,min = 0,max = 10)

```

# Row for contact
### Contact Rate


```{r}
#rate <- computeContactRate()
renderGauge({
  gauge(input$rate, min = 0, max = 100, symbol="%",label = "Contact Rate" ,gaugeSectors(success = c(80, 100), warning = c(40, 79), danger = c(0, 39)))
})

```

# Row for Rating
### Average Rating

```{r}
renderGauge({
  gauge(input$rating, label = "Average Rating",min = 0, max = 50, symbol='%',gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)))
})

```

# Row for Cancellations
### Cancellations

```{r}

renderGauge({
  gauge(input$cancellations, label = "Cancellations",min = 0, max = 10, symbol = '%', gaugeSectors(success = c(0, 2), warning = c(3, 6), danger = c(7, 10)))
})

```


```{r}
#rmarkdown::run("flexdashboard_guage.Rmd")
```

